### ISSUE TITLE
Sugestão de distribuição do pacote

### ISSUE THREAD

**Issue by leomaralha** [eloiguerra-yd/santillana-edusfera-logger#3]
Existe a possibilidade de fazermos com que código-fonte esteja disponivel via um gerenciador de pacotes?

**Comment by eloiguerra-yd** [comment]
É uma possibilidade, ainda não a estudamos, estamos priorizando por agora deixar como submodule por precisar de menos permissões com relação a burocracia de quem vai manter o pacote. configurar esse permissionamento e derivados. Mas novidades em breve
